export interface IPostedBy {
	_id: string;
	image: string;
	userName: string;
}

export interface IComment {
	_key: string;
	comment: string;
	postedBy: IPostedBy;
}

export interface ILike {
	_key: string;
	_ref: string;
	_type: 'reference';
}

export interface IPost {
	_id: string;
	caption: string;
	comments: IComment[];
	likes: ILike[];
	postedBy: IPostedBy;
	userId: string;
	video: {
		asset: {
			_id: string;
			url: string;
		};
	};
}

export interface ICommentData {
	userId: string;
	comment: string;
}

export interface ILikeData {
	userId: string;
	postId: string;
	like: boolean;
}

//* how to quickly create type - timestamp 7:37 - https://www.youtube.com/watch?v=tZK7vZifPp0
// Generated by https://quicktype.io

/* export interface Post {
  _id:      string;
  caption:  string;
  comments: Comment[];
  likes:    Like[];
  postedBy: PostedBy;
  userId:   string;
  video:    Video;
}

export interface Comment {
  _key:     string;
  comment:  string;
  postedBy: PostedBy;
}

export interface PostedBy {
  _id:      string;
  image:    string;
  userName: string;
}

export interface Like {
  _key:  string;
  _ref:  string;
  _type: string;
}

export interface Video {
  asset: Asset;
}

export interface Asset {
  _id: string;
  url: string;
} */
